name: Build Kivy APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk wget git build-essential \
          libssl-dev libffi-dev python3-dev zlib1g-dev libncurses5 libstdc++6 cmake
        pip install --upgrade pip
        pip install buildozer cython

    - name: Init Buildozer & copy main.py
      run: |
        buildozer init
        cp main.py .
        sed -i 's/^# *requirements = python3/requirements = python3,kivy/' buildozer.spec
        sed -i 's/^# *android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec
        sed -i 's/^# *source.include_exts.*/source.include_exts = py,png,jpg,kv/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: baby-wardrobe-apk
        path: bin/*.apk
