name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-11-jdk wget git build-essential \
          libssl-dev libffi-dev python3-dev zlib1g-dev libncurses5 libstdc++6 cmake
        pip install buildozer cython

    - name: Initialize Buildozer
      run: |
        buildozer init
        sed -i 's/^# *source.include_exts/source.include_exts = py,png,jpg,kv/' buildozer.spec
        sed -i 's/^# *requirements.*/requirements = kivy/' buildozer.spec
        sed -i 's/^# *android.permissions = INTERNET/android.permissions = INTERNET/' buildozer.spec

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: baby-wardrobe-apk
        path: bin/*.apk
